/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BoletoGarantidoRouteImport } from './routes/boleto-garantido'
import { Route as AntecipacaoDeRecebiveisRouteImport } from './routes/antecipacao-de-recebiveis'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletoGarantidoRoute = BoletoGarantidoRouteImport.update({
  id: '/boleto-garantido',
  path: '/boleto-garantido',
  getParentRoute: () => rootRouteImport,
} as any)
const AntecipacaoDeRecebiveisRoute = AntecipacaoDeRecebiveisRouteImport.update({
  id: '/antecipacao-de-recebiveis',
  path: '/antecipacao-de-recebiveis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/antecipacao-de-recebiveis': typeof AntecipacaoDeRecebiveisRoute
  '/boleto-garantido': typeof BoletoGarantidoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/antecipacao-de-recebiveis': typeof AntecipacaoDeRecebiveisRoute
  '/boleto-garantido': typeof BoletoGarantidoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/antecipacao-de-recebiveis': typeof AntecipacaoDeRecebiveisRoute
  '/boleto-garantido': typeof BoletoGarantidoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/antecipacao-de-recebiveis'
    | '/boleto-garantido'
    | '/contato'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/antecipacao-de-recebiveis'
    | '/boleto-garantido'
    | '/contato'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/antecipacao-de-recebiveis'
    | '/boleto-garantido'
    | '/contato'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntecipacaoDeRecebiveisRoute: typeof AntecipacaoDeRecebiveisRoute
  BoletoGarantidoRoute: typeof BoletoGarantidoRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boleto-garantido': {
      id: '/boleto-garantido'
      path: '/boleto-garantido'
      fullPath: '/boleto-garantido'
      preLoaderRoute: typeof BoletoGarantidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antecipacao-de-recebiveis': {
      id: '/antecipacao-de-recebiveis'
      path: '/antecipacao-de-recebiveis'
      fullPath: '/antecipacao-de-recebiveis'
      preLoaderRoute: typeof AntecipacaoDeRecebiveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntecipacaoDeRecebiveisRoute: AntecipacaoDeRecebiveisRoute,
  BoletoGarantidoRoute: BoletoGarantidoRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
