/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesPixParceladoRouteImport } from './routes/solucoes/pix-parcelado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesPixParceladoRoute = SolucoesPixParceladoRouteImport.update({
  id: '/solucoes/pix-parcelado',
  path: '/solucoes/pix-parcelado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solucoes/pix-parcelado': typeof SolucoesPixParceladoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solucoes/pix-parcelado': typeof SolucoesPixParceladoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solucoes/pix-parcelado': typeof SolucoesPixParceladoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solucoes/pix-parcelado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solucoes/pix-parcelado'
  id: '__root__' | '/' | '/solucoes/pix-parcelado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolucoesPixParceladoRoute: typeof SolucoesPixParceladoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/pix-parcelado': {
      id: '/solucoes/pix-parcelado'
      path: '/solucoes/pix-parcelado'
      fullPath: '/solucoes/pix-parcelado'
      preLoaderRoute: typeof SolucoesPixParceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolucoesPixParceladoRoute: SolucoesPixParceladoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
